/**
 * Multi-tenant intake config — sprint C.S.1.6.5.
 *
 * The Carbon Specialty intake agent used to run off a single hardcoded
 * system prompt (`src/lib/carbon-system-prompt.ts`, removed in this
 * sprint). This module defines the tenant-config contract: every
 * brokerage that wants a Carbon-style AI intake agent ships a
 * `TenantIntakeConfig` object, registers it in `./registry.ts`, and
 * flips its id into the `ACTIVE_TENANTS` env var. No code deploy.
 *
 * `buildSystemPrompt` (src/lib/system-prompt-builder.ts) is the pure
 * function that turns one of these configs into the full Anthropic
 * system prompt string.
 *
 * NOTE on `extendedSections`: the structured fields below model the
 * 80% of an intake agent that every brokerage shares. The incumbent
 * tenant (Carbon Specialty) carries a richer C.S.1.7.1 habitational
 * COPE prompt — hallucination guardrails, address-correction handling,
 * portfolio detection, passive listeners, batched-ask mechanics,
 * pricing-language rules — that the structured shape cannot express
 * losslessly. `extendedSections` is the escape hatch: free-form prose
 * blocks injected verbatim by the builder. Simple future tenants leave
 * it undefined and rely on the structured fields alone.
 */

/** A hard-stop condition. When any `matchPatterns` entry is found
 *  (case-insensitive substring) the agent stops intake and routes the
 *  prospect to a human specialist. */
export interface HandoffTrigger {
  id: string;
  /** Plain strings — checked case-insensitively in buildSystemPrompt. */
  matchPatterns: string[];
  reason:
    | "coverage-interpretation"
    | "active-loss"
    | "litigation"
    | "portfolio-too-large"
    | "out-of-scope";
  /** What the bot says before routing. */
  specialistMessage: string;
}

/** One thing the intake agent collects from the prospect. */
export interface IntakeField {
  id: string;
  label: string;
  required: boolean;
  /** How the bot asks for this field. */
  conversational: string;
  notes?: string;
}

/** A free-form prose block injected verbatim into the system prompt.
 *  Used by `TenantIntakeConfig.extendedSections` — the incumbent-
 *  fidelity escape hatch (see module docstring). */
export interface TenantPromptSection {
  heading: string;
  body: string;
}

/** The complete configuration for one brokerage's intake agent. */
export interface TenantIntakeConfig {
  id: string;
  name: string;
  tagline?: string;
  active: boolean;

  agent: {
    /** Opening message verbatim. */
    greeting: string;
    /** String that signals intake is complete. */
    wrapUpSentinel: string;
    /** Tone paragraph injected into the prompt. */
    toneNotes: string;
  };

  scope: {
    specialties: string[];
    geography: string[];
    outOfScopeMessage: string;
  };

  intake: {
    fields: IntakeField[];
    hardHandoffTriggers: HandoffTrigger[];
    portfolioTivLimitUsd?: number;
    /** e.g. "a Carbon specialist". */
    specialistLabel: string;
    /** e.g. "within 1 business day". */
    followUpSla: string;
  };

  /** Exactly 3. Concatenated POST-LLM-generation, never generated by
   *  the model. See `buildSystemPrompt` + the /api/chat route. */
  disclaimers: [string, string, string];

  /** Empty string until C.S.1.7 data lands. Appended to the prompt as
   *  a dedicated section by `buildSystemPrompt` when populated. */
  rateBandYaml?: string;

  output: {
    summaryHeader: string;
    /** Template string with {{camelCase}} placeholders. */
    summaryTemplate: string;
  };

  routing: {
    amsTarget?: "nowcerts" | "ezlynx" | "applied-epic" | "webhook" | "email-only";
    webhookUrl?: string;
    notificationEmail: string;
  };

  /** C.S.1.6.5 incumbent-fidelity escape hatch — see module docstring.
   *  Each entry is injected verbatim by `buildSystemPrompt` between the
   *  handoff-trigger section and the wrap-up instructions. Optional;
   *  omit for tenants whose intake the structured fields fully cover. */
  extendedSections?: TenantPromptSection[];
}
